[package]
name = "webscraper-rs"
version = "0.1.0"
authors = ["leon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4.3"
postgres = "0.17.5"
postgres-native-tls = "0.3.0"
native-tls = "0.2.4"